# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  compile: false
  source_path: client
  cache_manifest: false

development:
  <<: *default
  public_output_path: webpack/development
  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    host: localhost
    port: 3035
    hmr: true

test:
  <<: *default
  public_output_path: webpack/test

production:
  <<: *default
  public_output_path: webpack/production
  cache_manifest: true
